name: dbt-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Create temporary profile
        run: |
          cat > profiles.yml << EOF
          ga4_analytics:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: dummy-project
                dataset: dummy_dataset
                threads: 1
                keyfile: dummy.json
          EOF

      - name: Install packages
        run: dbt deps --profiles-dir .

      - name: Validate project
        run: dbt parse --profiles-dir .
